### ISSUE TITLE
Issue on a Mac with extension

### ISSUE THREAD

**Issue by robboz4** [BvdP/elliptical-box-maker#6]
Hi!

I'm getting this issue when trying to use your plugin in Inkscape on a Mac:
Traceback (most recent call last):

File ell_box.py, line 230, in <module>
effect.affect()
File"/application/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 278, in affect

Not sure what might be wrong.

The extension shows up under the laser tools drop down under extensions in Inkscape. The other tools I installed work fine. 

Info comes from an Instructables article:

https://www.instructables.com/id/The-Ultimate-Guide-to-Laser-cut-Box-Generators/

Any help would be appreciated. Thanks

**Comment by BvdP** [comment]
This should be fixed in the newest version (which still doesn't work for Inkscape 1.0).
