### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vmario89** [BvdP/elliptical-box-maker#7]
Hi dude,
i love this plugin. You did not apply some license to this repository.

May i use it for some remix? Most InkScape plugins are licensed by GPL v2/v3 or MIT License. Would be happy if you add some license to this repo.

regards, Mario

**Comment by BvdP** [comment]
Hello Mario

Your issue made me finally add a license (I picked MIT).

In any case, feel free to use this code any way you see fit.

Also note that I just released a new version that involves quite a lot of code changes (but no new features). Next version will be Inkscape 1.0 compatibility.

Regards
Bastaan
